name: validation
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  dio: ^4.0.6
  dropdown_button2: ^1.9.1
  flutter_svg: ^1.1.4
  flutter_svprogresshud: ^1.0.0
  future_progress_dialog: ^0.2.1
  pin_code_fields: ^7.4.0
  flutter_spinkit: ^5.1.0
  bot_toast: ^4.0.3
  image_picker: ^0.8.6
  timeago: ^3.5.0
  shared_preferences: ^2.0.15
  firebase_messaging: ^14.1.2
  video_player: ^2.4.5
  chewie: ^1.3.4
  youtube_player_flutter: ^8.0.0
  firebase_core: ^2.3.0

  flutter_local_notifications: ^12.0.4
  firebase_auth: ^4.1.4
  fluttertoast: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
    - family: medium
      fonts:
        - asset: assets/fonts/WorkSans-Medium.ttf
    - family: bold
      fonts:
        - asset: assets/fonts/WorkSans-Bold.ttf
    - family: semi
      fonts:
        - asset: assets/fonts/WorkSans-SemiBold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
